# -*- coding: utf-8 -*-
"""korea-ipa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQOAGb8Zkz8lPA-8NGJ-Bmf2ttvaKiNS
"""

!pip install epitran

import epitran
import ipywidgets as widgets
from IPython.display import display, clear_output

# 한국어 모델
epi = epitran.Epitran('kor-Hang')

def to_ipa(text):
    return epi.transliterate(text)

# Create a text area for input
text_input = widgets.Textarea(
    value='',
    placeholder='여기에 텍스트를 입력하세요 (예: 반갑습니다)',
    description='한국어 텍스트:',
    disabled=False,
    layout=widgets.Layout(width='auto', height='100px')
)

# Create a button for conversion
convert_button = widgets.Button(
    description='IPA로 변환하기',
    disabled=False,
    button_style='primary', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Click to convert to IPA',
    icon='refresh' # (FontAwesome names)
)

# Create an output widget to display results
output_widget = widgets.Output()

# Define the conversion function to be called on button click
def on_convert_button_clicked(b):
    with output_widget:
        clear_output()
        if text_input.value:
            ipa_result = to_ipa(text_input.value)
            print(f"IPA: {ipa_result}")
        else:
            print("텍스트를 입력해주세요.")

# Link the button click to the function
convert_button.on_click(on_convert_button_clicked)

# Display the widgets
display(text_input, convert_button, output_widget)